### ISSUE TITLE
Documentation format

### ISSUE THREAD

**Issue by giodegas** [EMICVL/Discussions#2]
Please, consider rewriting all EMICVL related documentation that is saved into each team repository in the MarkDown format:

http://help.github.com/articles/working-with-advanced-formatting/

Avoid using office formats (.ppt, .doc) , or at least save a PDF version of each office file.

By the end of the project, all documentation will have to stay readable online in MarkDown format.

**Comment by giodegas** [comment]
Please review, comment and discuss the general guide lines for the final Team Repository structure describe in http://github.com/EMICVL/ProjectDocumentation

**Comment by tomazam1** [comment]
Dear Giovanni,

 

The guide lines on

https://github.com/EMICVL/ProjectDocumentation/blob/master/README.md

are fine for me. 

 

Just a note regarding the File Formats section:

I am OK with collada, but why not to allow also the OBJ and FBX file formats ? I think that collada (dae extension ?) and fbx are very similar.

 

Thank you for your work!

 

Tomaz

**Comment by giodegas** [comment]
COLLADA format is a general purpose format that would allow anybody in the future to reuse the EMICVL assets in any other virtual reality engine, other than Unity. The binary versions will be already present in the Unity assets folders in the preferred Unity format for 3D objects.
